config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :orders do
    get '/change_status/:status', to: 'orders#change_status', as: :change_status, on: :member
    resources :messages
  end
  post '/orders/welcome', to: 'welcome#create_order', as: :welcome_orders

  resources :revisions
  resources :worktypes
  resources :parts

  resources :specialities
  devise_for :users, path_names: { sign_up: '/sign_up/:role' }

  scope '/admin' do
    resources :users do
      get '/manage', to: 'users#manage', as: :manage, on: :collection
    end
  end

  scope '/dashboard' do 
    get '', to: 'dashboard#index', as: :dashboard_index
    get 'create_order', to: 'dashboard#create_order', as: :dashboard_create_order
  end

  root 'welcome#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.role == 'Admin'
      can :manage, :all
    elsif user.role == 'Manager'
      can :manage, [Order, Part, Message, Revision]
      can :read, [Client, Employee]
    elsif user.role == 'Client'
      can :create, [Order, Message, Revision]
      can [:read, :update], Order, client_id: user.id
      can :read, Revision, order: { client_id: user.id }
      can :update, Revision, order: { client_id: user.id }, status: 'moderation'
      can :read, Message, receiver_id: user.id, status: 'approved'
      can :read, Message, sender_id: user.id
    elsif user.role == 'Employee'
      can :read, Order, employee_id: user.id
      can :read, Order do |order|
        order.status == 'employee_searching'
      end
      can :read, Revision, order: {employee_id: user.id}, status: 'approved'
      can :create, Message
      can :read, Message, receiver_id: user.id, status: 'approved' 
      can :read, Message, sender_id: user.id
    end

    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < User
end

app/models/client.rb
class Client < User
  has_many :orders, class_name: "Order", foreign_key: "client_id"
end

app/models/employee.rb
class Employee < User
  belongs_to :speciality
  has_many :orders, class_name: "Order", foreign_key: "employee_id"
end

app/models/manager.rb
class Manager < User
  has_many :orders, class_name: "Order", foreign_key: "manager_id"
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :sender
  belongs_to :receiver
  belongs_to :order
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :worktype
  belongs_to :speciality
  belongs_to :client, class_name: "Client"
  belongs_to :employee, class_name: "Employee"
  belongs_to :manager, class_name: "Manager"
  has_many :parts, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :revisions, dependent: :destroy

  enum status: %i[moderation approved employee_searching prepayment_waiting in_work solved finished]

  def display_status
    I18n.t("activerecord.attributes.#{self.class.name.downcase}.statuses.#{status}", default: status.titleize)
  end
 
  def self.status_names_for_select
    names = []
    statuses.keys.each do |status|
      display_name = I18n.t("activerecord.attributes.#{self.name.downcase}.statuses.#{status}", default: status.titleize)
      names << [display_name, status]
    end
    names
  end
end

app/models/part.rb
class Part < ActiveRecord::Base
  belongs_to :order
  has_attached_file :file
  validates_attachment_file_name :file, :matches => [/docx?\Z/, /pdf\Z/, /xlsx?\Z/]
end

app/models/revision.rb
class Revision < ActiveRecord::Base
  has_attached_file :document, default_url: false
  do_not_validate_attachment_file_type :document
  validates :comment, presence: true
  validates :order_id, presence: true
  belongs_to :order

  enum status: %i[moderation approved denied]
end

app/models/speciality.rb
class Speciality < ActiveRecord::Base
  has_many :employees
  has_many :orders
  def to_s
    self.name
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  ROLES = ['admin', 'manager', 'employee', 'client']
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable
  self.inheritance_column = 'role'

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end
end

app/models/worktype.rb
class Worktype < ActiveRecord::Base
  has_many :orders
  def to_s
    self.name
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    case current_user.role
    when 'Admin'
      redirect_to users_path
    when 'Client'
      @orders = current_user.orders.paginate(page: params[:page], per_page: 15)
      render 'dashboard/client/orders'
    when 'Manager'
      @orders = Order.paginate(page: params[:page], per_page: 15)
      render 'dashboard/manager/orders'
    when 'Employee'
      @orders = current_user.orders.paginate(page: params[:page], per_page: 15)
      render 'dashboard/employee/my_orders'
    end
  end
  def create_order
    @order = Order.new
    render "dashboard/#{current_user.role.downcase}/create_order"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end
module ActionView
  module Helpers
    class FormBuilder 
      def date_select(method, options = {}, html_options = {})
        existing_date = @object.send(method) 
        formatted_date = existing_date.to_date.strftime("%d.%m.%Y") if existing_date.present?
        @template.content_tag(:div, class: "input-group") do    
          text_field(method, value: formatted_date, class: "form-control datepicker", "data-date-format": "DD.MM.YYYY") +
          @template.content_tag(:span, @template.content_tag(:span, "", class: "glyphicon glyphicon-calendar"), class: "input-group-addon")
        end
      end

      def datetime_select(method, options = {}, html_options = {})
        existing_time = @object.send(method) 
        formatted_time = existing_time.to_time.strftime("%d.%m.%Y %H:%M") if existing_time.present?
        @template.content_tag(:div, class: "input-group") do    
          text_field(method, value: formatted_time, class: "form-control datetimepicker", "data-date-format": "DD.MM.YYYY HH:mm") +
          @template.content_tag(:span, @template.content_tag(:span, "", class: "glyphicon glyphicon-calendar"), class: "input-group-addon")
        end
      end
    end
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/revisions_helper.rb
module RevisionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/worktypes_helper.rb
module WorktypesHelper
end

app/views/dashboard/_contacts.html.erb
<div class="btn-group <%= html_class %>" role="group" aria-label="...">
  <button type="button" class="btn btn-default"><%= user.role %></button>
  <button type="button" class="btn btn-default">
    <span class="glyphicon glyphicon-user" aria-hidden="true"></span> <%= user.name %>
  </button>
  <button type="button" class="btn btn-default">
    <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> <%= user.email %>
  </button>
  <button type="button" class="btn btn-default">
    <span class="glyphicon glyphicon-earphone" aria-hidden="true"></span> <%= user.phone %>
  </button>
</div>

app/views/dashboard/_header.html.erb
<div class="header">
  <br/>
  <div class="container">
    <div class="row">
      <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
        <p><span class="glyphicon glyphicon-picture" aria-hidden="true"></span> LOGO</p>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
        <div class="media">
          <div class="media-left media-middle">
            <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>
          </div>
          <div class="media-body">
            <h4 class="media-heading">Регистрация</h4>
            <p>Добро пожаловать, <%= current_user.name %>!</p>
            <%= link_to('Выйти', destroy_user_session_path, method: :delete) %>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
        <div class="media">
          <div class="media-left media-middle">
            <span class="glyphicon glyphicon-phone" aria-hidden="true"></span>
          </div>
          <div class="media-body">
            <h4 class="media-heading">Свяжитесь с нами</h4>
            <p>Телефон: <a href="#">+375 29 637 04 02</a></p>
            <p>Телефон: <a href="#">+375 29 637 03 67</a></p>
            <a href="#">Обратная связь</a>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
        <div class="media">
          <div class="media-left media-middle">
            <span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span>
          </div>
          <div class="media-body">
            <h4 class="media-heading">Как нас найти</h4>
            <p>Минск, ул. Тимирязева ,67.</p>
            <a href="#">Карта</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="page-header">
  <h1 class="text-center">Страница <%= role %></h1>
</div>

app/views/dashboard/_order.html.erb
<%= render "dashboard/#{current_user.role.downcase}/header" %>
<%= render 'layouts/alerts' %>
<div class="container">
  <!-- ================================================== -->
  <div class="page-header">
    <h2 class="text-center">Заказ №<%= @order.id%>
      <% if can? :manage, @order %>
        <%= link_to 'Завершить заказ', change_status_order_path(@order, :finished), class: "btn btn-info" %>
      <% end %>
    </h2>
  </div>
  <!-- ================================================== -->
  <% client = @order.client; employee = @order.employee %>
  <% if (can? :read, employee) || (can? :read, client)  %>
  <div class="panel panel-default">
    <div class="panel-body">
      <% if client %>
        <% if can? :read, client %>
          <%= render partial: 'dashboard/contacts', locals: {user: client, html_class: ''} %>
        <% end %>
      <% end %>
      <% if employee %>
        <% if can? :read, employee %>
          <%= render partial: 'dashboard/contacts', locals: {user: employee, html_class: 'pull-right'} %>
        <% end %>
      <% end %>
    </div>
  </div>
  <% end %>
  <!-- ================================================== -->
  <div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
      <div class="panel panel-default">
        <div class="panel-body">
          <!-- ================================================== -->
          <div>
            <button type="button" class="btn btn-success pull-left"><%= @order.display_status %></button>
            <button type="button" class="btn btn-primary pull-right">Поиск исполнителя</button>
          </div>
          <div class="clearfix"></div>
          <h3>Примечания (по всему заказу)</h3>
          <form>
            <div class="form-group">
              <label for="note">Заметки</label>
              <textarea class="form-control" rows="3" id="note"></textarea>
            </div>
            <div class="form-group">
              <label for="note_author">Заметки для автора</label>
              <textarea class="form-control" rows="3" id="note_author"></textarea>
            </div>
            <!-- <button type="submit" class="btn btn-default">Submit</button> -->
          </form>
          <!-- ================================================== -->
          <% if can? :create, Part %>
            <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
              <% if @order.parts %>
                <% @order.parts.each do |part| %>
                  <%= render partial: 'parts/form', locals: {part: part} %>
                <% end %>
              <% end %>
              <%= render partial: 'parts/form', locals: {part: Part.new } %>
            </div>
          <% end %>
          <!-- panel-group -->
          <!--<button type="button" class="btn btn-primary btn-lg btn-block">Добавить часть</button>-->
          <div class="clearfix"></div>
          <!--<br/>-->
          <!-- ================================================== -->
          <% if can? :read, Revision %>
            <div class="panel panel-default">
              <div class="panel-heading">
                <h3 class="panel-title">Доработки</h3>
              </div>
              <div class="panel-body">
                <%= render partial: 'revisions/index', locals: { revisions: Revision.all.order(:created_at) } %>
                <% if can? :create, Revision %>
                  <%= render partial: 'revisions/new', locals: { revision: Revision.new } %>
                <% end %>
              </div>
            </div>
          <% end %>
          <!-- ================================================== -->
        </div>
      </div>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
      <% if can? :manage, @order %>
        <div class="panel panel-default">
          <div class="panel-body">
            <!-- ================================================== -->
            <%= form_for(@order) do |f| %>
              <div>
                <p class="pull-left">Сроки выполнения</p>
                <%= f.button "Сохранить", class: 'btn btn-primary pull-right' %>
              </div>
              <div class="clearfix"></div>
              <br/>
              <div class="row">
                <div class="form-group col-lg-4">
                  <%= f.label :deadline %>
                  <%= f.date_select :deadline %>
                </div>
                <div class="form-group col-lg-4">
                  <%= f.label :inform_date %>
                  <%= f.datetime_select :inform_date %>
                </div>
                <div class="form-group col-lg-4">
                  <%= f.label :employee_deadline %>
                  <%= f.datetime_select :employee_deadline %>
                </div>
              </div>
            <% end %>
            <!-- ================================================== -->
          </div>
          <!-- panel-body -->
        </div>
      <% end %>
      <!-- panel panel-default -->
      <!-- ================================================== -->
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="well well-sm">
            <div class="media">
              <div class="media-left media-middle">
                <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
              </div>
              <div class="media-body">
                <h4 class="media-heading"><span class="text-primary">Администратор </span>| <span class="text-muted">20.10.2015 </span></h4>
                <p>Гирокомпас устойчив. Вращение вращает устойчивый интеграл от переменной величины. Согласно теории устойчивости движения векторная форма стационарно переворачивает математический маятник. Центр сил представляет собой твердый крен.</p>
              </div>
            </div>
          </div>
          <div class="well well-sm">
            <div class="media">
              <div class="media-left media-middle">
                <span class="glyphicon glyphicon-piggy-bank" aria-hidden="true"></span>
              </div>
              <div class="media-body">
                <h4 class="media-heading"><span class="text-success">Заказчик </span>| <span class="text-muted">21.10.2015 </span></h4>
                <p>В самом общем случае угол тангажа методически требует большего внимания к анализу ошибок, которые даёт периодический курс, составляя уравнения Эйлера для этой системы координат.</p>
              </div>
            </div>
          </div>
          <div class="well well-sm">
            <div class="media">
              <div class="media-left media-middle">
                <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
              </div>
              <div class="media-body">
                <h4 class="media-heading"><span class="text-primary">Администратор </span>| <span class="text-muted">22.10.2015 </span></h4>
                <p>Вращение вращает устойчивый интеграл от переменной величины.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- panel -->
      <!-- ================================================== -->
      <%= render 'messages/form' %>
      <!-- panel -->
      <!-- ================================================== -->
      <div class="panel panel-default">
        <div class="panel-body">
          <h3>Оплаты</h3>
          <form>
            <table class="table table-striped">
              <tr>
                <td>Стоимость проекта</td>
                <td><input type="number"></td>
                <td>Стоимость для автора</td>
                <td><input type="number"></td>
              </tr>
              <tr>
                <td>Получено от клиента</td>
                <td><strong>1 000 000</strong></td>
                <td>Оплачено работы</td>
                <td></td>
              </tr>
              <tr>
                <td>Выписать счет</td>
                <td><input type="number"></td>
                <td>Оптравить на оплату</td>
                <td><input type="number"></td>
              </tr>
              <tr>
                <td>Стоит на оплате</td>
                <td>1000</td>
                <td>Суммарно на оплату</td>
                <td>0</td>
              </tr>
            </table>
            <div class="row">
              <div class="col-sm-7 col-xs-12">
                <p>Подтвердить платеж</p>
                <button type="button" class="btn btn-default">Подтвердить</button>
                <button type="button" class="btn btn-default">Отмена</button>
                <button type="button" class="btn btn-info">Чек 1</button>
              </div>
              <div class="col-sm-5 col-xs-12">
                <button type="submit" class="btn btn-primary pull-right">Сохранить</button>
              </div>
            </div>
          </form>
        </div>
      </div>
      <!-- ================================================== -->
    </div>
    <!-- col-lg-8 -->
  </div>
  <!-- row -->
  <!-- ================================================== -->
  <button class="btn btn-default btn-block btn-lg" type="button" data-toggle="collapse" data-target="#order_info" aria-expanded="false" aria-controls="order_info">
    Информация о заказе <span class="glyphicon glyphicon-menu-down" aria-hidden="true"></span>
  </button>
  <div class="collapse" id="order_info">
    <div class="well">
      <div class="row">
        <div class="col-lg-6 col-md-7 col-sm-10 col-xs-12">
          <form>
            <div class="form-group">
              <label for="">Специальность</label>
              <select class="form-control">
                <option>Программирование</option>
                <option>Нанотехнологии</option>
                <option>Контроль разума</option>
              </select>
            </div>
            <div class="form-group">
              <label for="">Наименование</label>
              <input type="test" class="form-control" id="" placeholder="Наименование">
            </div>
            <div class="form-group">
              <label for="">Содержание</label>
              <textarea class="form-control" rows="5"></textarea>
            </div>
            <div class="form-group">
              <label for="">Дополнительные требования или рекомендации</label>
              <textarea class="form-control" rows="5"></textarea>
            </div>
            <p>Сроки выполнения</p>
            <table class="table table-striped">
              <tr>
                <th>Наименование</th>
                <th>Дата/время</th>
              </tr>
              <tr>
                <td>Дата оформления</td>
                <td><input type="datetime-local"></td>
              </tr>
            </table>
            <button type="submit" class="btn btn-primary">Сохранить</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  <br/>
  <!-- ================================================== -->
</div>
<!-- container -->

app/views/dashboard/admin/_header.html.erb
<div class="btn-group btn-group-justified btn-group-lg" role="group" aria-label="...">
  <div class="btn-group" role="group">
    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Проекты
            <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <li><a href="zakazy.html">Заказы</a></li>
      <li><a href="create_order.html">Создать заказ</a></li>
    </ul>
  </div>
  <div class="btn-group" role="group">
    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Пользователи
            <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <li>
        <%= link_to('Пользователи',users_path) %>
      </li>
    </ul>
  </div>
  <div class="btn-group" role="group">
    <button type="button" class="btn btn-default"><a href="events.html">События</a></button>
  </div>
  <div class="btn-group" role="group">
    <button type="button" class="btn btn-default"><a href="#">Бухгалтерия</a></button>
  </div>
  <div class="btn-group" role="group">
    <%= link_to('Выход (admin)', destroy_user_session_path, method: :delete, class: 'btn btn-default') %> 
    <!--<button type="button" class="btn btn-default"><a href="#">Выход (admin)</a></button>-->
  </div>
</div>

app/views/dashboard/admin/create_order.html.erb
<%= render "dashboard/#{current_user.role.downcase}/header" %>
<div class="panel panel-default">
  <div class="panel-body">
	<%= render 'orders/form' %>
  </div>
</div>

app/views/dashboard/index.html.erb
<%= render "dashboard/#{current_user.role.downcase}/header" %>