config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :orders do
    get '/change_status/:status', to: 'orders#change_status', as: :change_status, on: :member
    resources :messages
  end
  post '/orders/welcome', to: 'welcome#create_order', as: :welcome_orders

  resources :revisions
  resources :worktypes
  resources :parts

  resources :specialities
  devise_for :users, path_names: { sign_up: '/sign_up/:role' }

  scope '/admin' do
    resources :users do
      get '/manage', to: 'users#manage', as: :manage, on: :collection
    end
  end

  scope '/dashboard' do 
    get '', to: 'dashboard#index', as: :dashboard_index
    get 'create_order', to: 'dashboard#create_order', as: :dashboard_create_order
  end

  root 'welcome#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.role == 'Admin'
      can :manage, :all
    elsif user.role == 'Manager'
      can :manage, [Order, Part, Message, Revision]
      can :read, [Client, Employee]
    elsif user.role == 'Client'
      can :create, [Order, Message, Revision]
      can [:read, :update], Order, client_id: user.id
      can :read, Revision, order: { client_id: user.id }
      can :update, Revision, order: { client_id: user.id }, status: 'moderation'
      can :read, Message, receiver_id: user.id, status: 'approved'
      can :read, Message, sender_id: user.id
    elsif user.role == 'Employee'
      can :read, Order, employee_id: user.id
      can :read, Order do |order|
        order.status == 'employee_searching'
      end
      can :read, Revision, order: {employee_id: user.id}, status: 'approved'
      can :create, Message
      can :read, Message, receiver_id: user.id, status: 'approved' 
      can :read, Message, sender_id: user.id
    end

    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < User
end

app/models/client.rb
class Client < User
  has_many :orders, class_name: "Order", foreign_key: "client_id"
end

app/models/employee.rb
class Employee < User
  belongs_to :speciality
  has_many :orders, class_name: "Order", foreign_key: "employee_id"
end

app/models/manager.rb
class Manager < User
  has_many :orders, class_name: "Order", foreign_key: "manager_id"
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :sender
  belongs_to :receiver
  belongs_to :order
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :worktype
  belongs_to :speciality
  belongs_to :client, class_name: "Client"
  belongs_to :employee, class_name: "Employee"
  belongs_to :manager, class_name: "Manager"
  has_many :parts, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :revisions, dependent: :destroy

  enum status: %i[moderation approved employee_searching prepayment_waiting in_work solved finished]

  def display_status
    I18n.t("activerecord.attributes.#{self.class.name.downcase}.statuses.#{status}", default: status.titleize)
  end
 
  def self.status_names_for_select
    names = []
    statuses.keys.each do |status|
      display_name = I18n.t("activerecord.attributes.#{self.name.downcase}.statuses.#{status}", default: status.titleize)
      names << [display_name, status]
    end
    names
  end
end

app/models/part.rb
class Part < ActiveRecord::Base
  belongs_to :order
  has_attached_file :file
  validates_attachment_file_name :file, :matches => [/docx?\Z/, /pdf\Z/, /xlsx?\Z/]
end

app/models/revision.rb
class Revision < ActiveRecord::Base
  has_attached_file :document, default_url: false
  do_not_validate_attachment_file_type :document
  validates :comment, presence: true
  validates :order_id, presence: true
  belongs_to :order

  enum status: %i[moderation approved denied]
end

app/models/speciality.rb
class Speciality < ActiveRecord::Base
  has_many :employees
  has_many :orders
  def to_s
    self.name
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  ROLES = ['admin', 'manager', 'employee', 'client']
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable
  self.inheritance_column = 'role'

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end
end

app/models/worktype.rb
class Worktype < ActiveRecord::Base
  has_many :orders
  def to_s
    self.name
  end
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  before_action :set_part, only: [:update, :destroy]
  load_and_authorize_resource
  def create
    part = Part.new(part_params)

    if part.save
      redirect_to :back, notice: 'Часть успешно создана'
    else
      redirect_to :back, notice: 'Ошибка'
    end
  end

  def update
    part = Part.find(params[:id])
    if part.update(part_params)
      redirect_to :back, notice: 'Часть успешно обновлена'
    else
      redirect_to :back, notice: 'Ошибка'
    end
  end

  def destroy
    Part.find(params[:id]).destroy
    redirect_to :back, notice: 'Часть усешно удален'
  end

  private
  def set_part
    @part = Part.find(params[:id])
  end

  def part_params
    params.require(:part).permit(:name, :deadline, :order_id, :description, :file, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end
module ActionView
  module Helpers
    class FormBuilder 
      def date_select(method, options = {}, html_options = {})
        existing_date = @object.send(method) 
        formatted_date = existing_date.to_date.strftime("%d.%m.%Y") if existing_date.present?
        @template.content_tag(:div, class: "input-group") do    
          text_field(method, value: formatted_date, class: "form-control datepicker", "data-date-format": "DD.MM.YYYY") +
          @template.content_tag(:span, @template.content_tag(:span, "", class: "glyphicon glyphicon-calendar"), class: "input-group-addon")
        end
      end

      def datetime_select(method, options = {}, html_options = {})
        existing_time = @object.send(method) 
        formatted_time = existing_time.to_time.strftime("%d.%m.%Y %H:%M") if existing_time.present?
        @template.content_tag(:div, class: "input-group") do    
          text_field(method, value: formatted_time, class: "form-control datetimepicker", "data-date-format": "DD.MM.YYYY HH:mm") +
          @template.content_tag(:span, @template.content_tag(:span, "", class: "glyphicon glyphicon-calendar"), class: "input-group-addon")
        end
      end
    end
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/revisions_helper.rb
module RevisionsHelper
end

app/helpers/specialities_helper.rb
module SpecialitiesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/worktypes_helper.rb
module WorktypesHelper
end

app/views/parts/_form.html.erb
<div class="panel panel-default">
  <%= form_for(part) do |f| %>
    <%= f.hidden_field :order_id, value: @order.id %>
    <div class="panel-heading" role="tab" id="headingOne">
      <div class="row">
        <div class="col-xs-6">
          <h4 class="panel-title">
            <% panel_title = part.name ? part.name : "Новая часть" %>
            <%= link_to panel_title, "#part#{part.id}", { role: "button", class: "collapsed",
                          "data-toggle": "collapse", "data-parent": "#accordion",
                          "aria-expanded": "true", "aria-controls": "part#{part.id}" } %>
          </h4>
        </div>
        <div class="col-xs-6">
          <div class="form-group">
            <%= f.datetime_select :deadline %>
          </div>
        </div>
      </div>
    </div>
    <div id="<%= "part#{part.id}" %>" class="panel-collapse collapse " role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body">
        <div class="form-group">
          <%= f.text_field :name, placeholder: 'Название части', class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.text_area :description, placeholder: 'Описание', class: 'form-control' %>
        </div>
        <div class="panel panel-default">
          <div class="panel-body">
            <p class="text-muted text-uppercase text-center"><strong>Перетащите файлы сюда</strong></p>
            <% if part.file.size %>
              <p class="text-primary"><%= link_to part.file_file_name, part.file.url %></p>
            <% end %>
            <div class="form-group">
              <%= f.file_field :file %>
              <!-- <input type="file" id="new_part_file"> -->
            </div>
          </div>
        </div>
        <br/>
        <%= f.button "Сохранить", class: 'btn btn-primary btn-lg btn-block' %>
        <% if part.id %>
          <%= link_to 'Удалить часть', part_path(part), method: :delete, class: "btn btn-danger btn-lg btn-block", data: { confirm: "Вы уверены?"} %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>