config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :orders do
    get '/change_status/:status', to: 'orders#change_status', as: :change_status, on: :member
    resources :messages
  end
  post '/orders/welcome', to: 'welcome#create_order', as: :welcome_orders

  resources :revisions
  resources :worktypes
  resources :parts

  resources :specialities
  devise_for :users, path_names: { sign_up: '/sign_up/:role' }

  scope '/admin' do
    resources :users do
      get '/manage', to: 'users#manage', as: :manage, on: :collection
    end
  end

  scope '/dashboard' do 
    get '', to: 'dashboard#index', as: :dashboard_index
    get 'create_order', to: 'dashboard#create_order', as: :dashboard_create_order
  end

  root 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  ROLES = ['admin', 'manager', 'employee', 'client']
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable
  self.inheritance_column = 'role'

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  def index
    # @users = User.where.not(id: current_user.id)
    @users = User.paginate(page: params[:page], per_page: 15)
    # @user_lists = {
    #   clients: Client.paginate(page: params[:page], per_page: 10),
    #   employees: Employee.paginate(page: params[:page], per_page: 10)
    # }
  end

  def manage
    # @users = User.where.not(id: current_user.id)
    @users = User.paginate(page: params[:page], per_page: 15)
    # @user_lists = {
    #   clients: Client.paginate(page: params[:page], per_page: 10),
    #   employees: Employee.paginate(page: params[:page], per_page: 10)
    # }
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Пользователь успешно создан."
      redirect_to users_path
    else
      render action: 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    parms = user_params
    parms.delete(:password) if parms[:password].blank?
    parms.delete(:password_confirmation) if parms[:password].blank? and parms[:password_confirmation].blank?
    if @user.update_attributes(parms)
      flash[:notice] = "Successfully updated User."
      redirect_to action: :index
    else
      render action: 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:notice] = "Successfully deleted User."
      redirect_to :back
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def user_params
    params.require(:user).permit(:role, :email, :password, :name, :phone, :skype, :city, :speciality_id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
  <% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="form-group">
  <%= f.label :role %><br />
  <%= f.collection_select :role, User::ROLES, :capitalize, :capitalize, { prompt: 'Выберите роль пользователя'}, { required: true, class: 'form-control' } %>
</div>
<div class="form-group">
  <%= f.label :email %><br />
  <%= f.email_field :email, autofocus: true, required: true, class: 'form-control', placeholder: 'E-mail' %>
</div>
<div class="form-group">
  <%= f.label :password %>
  <%= f.text_field :password, autocomplete: "off", class: 'form-control', placeholder: 'Пароль'%>
</div>
<div class="form-group">
  <%= f.label :name %><br />
  <%= f.text_field :name, class: 'form-control', placeholder: 'ФИО' %>
</div>
<div class="form-group">
  <%= f.label :phone %><br />
  <%= f.text_field :phone, class: 'form-control', placeholder: 'Телефон' %>
</div>
<div class="form-group hiddenable Client hidden">
  <%= f.label :city %><br />
  <%= f.text_field :city, class: 'form-control', placeholder: 'Город' %>
</div>
<div class="form-group hiddenable Employee hidden">
  <%= f.label :skype %><br />
  <%= f.text_field :skype, class: 'form-control', placeholder: 'Skype' %>
</div>
<div class="form-group hiddenable Employee hidden">
  <%= f.label :speciality_id %><br />
  <%= f.collection_select :speciality_id, Speciality.all, :id, :name, { prompt: 'Специализация'}, { class: 'form-control' } %>
</div>
<div class="checkbox">
  <%= f.label :activated %>
  <%= f.check_box :activated, style: "margin-left:-555px;" %>
</div>

app/views/users/_index.html.erb
<div role="tabpanel" class="tab-pane <%= klass %>" id="<%= role %>">
  <h2 class="text-center">All <%= role %></h2>
  <p class="text-right"><%= page_entries_info(users) %></p>
  <table class="table table-hover">
    <thead>
      <tr class="info">
        <th>Имя</th>
        <th>Электронная почта</th>
        <th>Телефон</th>
      </tr>
    </thead>
    <tbody>
      <% users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= user.phone %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <nav>
    <%= will_paginate users, previous_label: "&laquo;", next_label: "&raquo;", renderer: BootstrapPagination::Rails, params: {role: role} %>
  </nav>
</div>

app/views/users/edit.html.erb
<%= render 'dashboard/admin/header' %>
<p id="notice"><%= notice %></p>
<br>
<h1 class="text-center">Редактирование пользователя</h1>
<%= form_for @user, as: :user, url: user_path(@user) do |f| %>
  <%= render partial: 'form', :locals => { :f => f } %>
  <%= f.button "Сохранить", class: 'btn btn-primary' %>
  <%= link_to 'Назад', "javascript:history.back()", class: 'btn btn-default' %>
<% end %>

app/views/users/index.html.erb
<%= render 'dashboard/admin/header' %>
<p id="notice"><%= notice %></p>
<br>
<div class="container">
  <div class="btn-group btn-group-justified" role="group" aria-label="...">
    <div class="btn-group" role="group">
      <button type="button" class="btn btn-info">
        <%= link_to 'Управление пользователями', manage_users_path %>
      </button>
    </div>
    <div class="btn-group" role="group">
      <button type="button" class="btn btn-info"><a href="#">Настройка полей</a></button>
    </div>
    <div class="btn-group" role="group">
      <button type="button" class="btn btn-info"><a href="#">Список авторов</a></button>
    </div>
    <div class="btn-group" role="group">
      <button type="button" class="btn btn-info"><a href="#">Список заказчиков</a></button>
    </div>
  </div>
</div>
<br>
<div>
  <% active_role = params[:role] || 'client' %>
  <ul class="nav nav-tabs" role="tablist">
    <% ['client', 'employee'].each do |role| %>
    <% klass = 'active' if role == active_role %>
      <li role="presentation" class="<%= klass %> clickable">
        <%= link_to "#{role}", "##{role}", {"aria-controls": role, "role": "tab", "data-toggle": "tab" } %>
      </li>
    <% end %>
  </ul>
  <div class="tab-content">
    <% User::ROLES.each do |role| %>
      <% klass = 'active' if role == active_role %>
      <%= render partial: 'index', locals: { users: @users.where(role: role.capitalize), role: role, klass: klass } %>
    <% end %>
  </div>
</div>

app/views/users/manage.html.erb
<%= render 'dashboard/admin/header' %>
<p id="notice"><%= notice %></p>
<br>
<div class="container">
  <div class="btn-group btn-group-justified" role="group" aria-label="...">
    <div class="btn-group" role="group">
      <button type="button" class="btn btn-info">
        <%= link_to 'Новый', new_user_path %>
      </button>
    </div>
    <div class="btn-group" role="group">
      <button type="button" class="btn btn-info">
        <%= link_to 'Управление пользователями', manage_users_path %>
      </button>
    </div>
    <div class="btn-group" role="group">
      <button type="button" class="btn btn-info"><a href="#">Настройка полей</a></button>
    </div>
    <div class="btn-group" role="group">
      <button type="button" class="btn btn-info">
        <%= link_to 'Список пользователей', users_path %>
      </button>
    </div>
    <div class="btn-group" role="group">
      <button type="button" class="btn btn-info"><a href="#">Права пользователей</a></button>
    </div>
  </div>
</div>
<br/>
<!-- ================================================== -->
<div class="container">
  <div class="page-header">
    <h1 class="text-center">Управление пользователями</h1>
  </div>
  <!-- ================================================== -->
  <p class="text-right"><%= page_entries_info(@users) %></p>
  <table class="table table-hover">
    <tr class="info">
      <th>id</th>
      <!--<th>Логин</th>-->
      <th>Имя</th>
      <th>Электронная почта</th>
      <th>Дата регистрации</th>
      <th>Последний визит</th>
      <th>Супер пользователь</th>
      <th>Статус</th>
      <th></th>
    </tr>
    <!--
    <tr class="warning">
      <td><input type="text" id=""></td>
      <td><input type="text" id=""></td>
      <td><input type="text" id=""></td>
      <td><input type="datetime-local" id=""></td>
      <td><input type="datetime-local" id=""></td>
      <td>
        <select class="form-control">
          <option>Да</option>
          <option>Нет</option>
        </select>
      </td>
      <td>
        <select class="form-control">
          <option>Активирован</option>
          <option>Не активирован</option>
        </select>
      </td>
      <td></td>
    -->
  </tr>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.id %></td>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= user.created_at.strftime("%d.%m.%Y %H:%M") %></td>
      <td><%= user.last_sign_in_at.strftime("%d.%m.%Y %H:%M") if user.last_sign_in_at %></td>
      <td><%= user.role == 'Admin' ? 'Да' : 'Нет' %></td>
      <td><%= user.activated ? 'Активирован' : 'Не активирован' %></td>
      <td>
        <a href="#"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></a>
        <%= link_to '', edit_user_path(user), class: 'glyphicon glyphicon-edit', title: 'Редактровать' %>
        <%= link_to '', user_path(user), method: :delete, class: 'glyphicon glyphicon-remove', title: 'Удалить', data: { confirm: "Вы уверены?"} %>
      </td>
    </tr>
  <% end %>
</table>
<%= will_paginate @users, previous_label: "&laquo;", next_label: "&raquo;", renderer: BootstrapPagination::Rails %>
<!-- ================================================== -->
</div>
<!-- container -->

app/views/users/new.html.erb
<%= render 'dashboard/admin/header' %>
<p id="notice"><%= notice %></p>
<br>
<h1 class="text-center">Новый пользователь</h1>
<%= form_for @user, as: :user, url: users_path do |f| %>
  <%= render partial: 'form', :locals => { :f => f } %>
  <%= f.button "Создать", class: 'btn btn-primary' %>
  <%= link_to 'Назад', "javascript:history.back()", class: 'btn btn-default' %>
<% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>